In [1]:
4

4

In [2]:
print( max(2.4,2.0)   )
print( min(2.4, 2.0)  )
print( abs(-2.4)      )
print( len("abcde")   )

2.4
2.0
2.4
5


In [3]:
a=50.8
print([1,'hei',a])
len([1,'hei',a])

[1, 'hei', 50.8]


3

In [4]:
import numpy as np

In [5]:
np.exp(2)

7.38905609893065

In [6]:
np.exp(1)

2.718281828459045

In [7]:
np.exp(1)**5

148.41315910257657

In [8]:
np.exp(5)

148.4131591025766

In [9]:
def account_balance(x,r,T):
    return x*(1+r)**T

In [10]:
account_balance(100,0.2,2)

144.0

In [11]:
def account_balance_n(x,r,T,n):
    return x*(1+r/n)**(T*n)

In [12]:
print(account_balance_n(100,0.2,2,12))
print(account_balance_n(100,0.2,2,1))

148.69146179463576
144.0


In [13]:
account_balance_n(100,0.2,2,31536000)

149.18246858790133

In [14]:
def account_balance_exponential(x,r,T):
    return x*np.exp(r*T)

In [15]:
account_balance_exponential(100,0.2,2)

149.18246976412703

In [16]:
def f(x):
    return 2*x

In [17]:
print(f(8))            # printer resultatet av funksjonen når argumentet er 8
print(type(f))         # printer hvilken type objekt det er
print(type(f(5)))      # printer hvilken type resultate av funksjonen er

16
<class 'function'>
<class 'int'>


In [18]:
def hello():
    print('Hello world!')

hello()

Hello world!


In [19]:
hi=hello
hi()

Hello world!


In [20]:
def f(x,a=1.02e+2):
    return a*x

print(f"Innehaveren krevde i utgangspunkltet {f(5)} kroner for fem epler.\n"
     f"Det var alt for mye, så jeg tilbydde {f(5,1.02e-2)} kroner.\n"
     f"Vi ble til slutt enige om {f(5,1.02e+1)} kroner.\n")

Innehaveren krevde i utgangspunkltet 510.0 kroner for fem epler.
Det var alt for mye, så jeg tilbydde 0.051000000000000004 kroner.
Vi ble til slutt enige om 51.0 kroner.



In [21]:
args=(20,50)
f(*args)

1000

In [22]:
#Creating a function that returns total demand given a price p
def demand(x):
    return 125/(5+x)

In [23]:
#Creating a function that returns total supply given a price p
def supply(x):
    return x**2

In [24]:
def check():
    for i in range(1, 10):
        print(supply(i))

check()

1
4
9
16
25
36
49
64
81


In [25]:
def check():
    for i in range(1, 10):
        print(supply(i))

    for b in range(1, 10):
        print(demand(b))

check()

### En mer sofistikert måte å løse dette på er
import sympy as sp 

def difference(x):
    return demand(x) - supply(x)

# Bruk SymPy for å finne roten til differansefunksjonen
x = sp.symbols('x')
difference_expr = demand(x) - supply(x)
solution = sp.solve(difference_expr, x)

# Finn en reell og positiv løsning
quantum = [sol.evalf() for sol in solution if sol.is_real and sol > 0][0]
price = demand(quantum)

print(f"Kvantum som gir likhet mellom tilbud og etterspørsel: {quantum}")
print(f"Prisen ved dette kvantumet: {price}")

1
4
9
16
25
36
49
64
81
20.833333333333332
17.857142857142858
15.625
13.88888888888889
12.5
11.363636363636363
10.416666666666666
9.615384615384615
8.928571428571429


Kvantum som gir likhet mellom tilbud og etterspørsel: 3.77438833123346
Prisen ved dette kvantumet: 14.2460072749513


In [26]:
# Funksjon for budsjett
def budget(x, b):
    print(f'Du har {b} kr i budsjett')
    print(f'Når du har brukt {x} kr, har du')
    print(f'{b-x} kr igjen.')

budget(100, 1000)

Du har 1000 kr i budsjett
Når du har brukt 100 kr, har du
900 kr igjen.


In [27]:
def parking_cost(time_period, p):
    hh,mm,ss=int(time_period[0:2]),int(time_period[3:5]),int(time_period[6:])
    time_decimal = hh + (mm/60) + (ss/(60*60))
    return time_decimal*p

time_period = "02:22:31"
p = 120

print(f"Parkeringstid: {time_period}, pris per time: {p} kroner, parkeringskostnad: {parking_cost(time_period, p)} kroner")

Parkeringstid: 02:22:31, pris per time: 120 kroner, parkeringskostnad: 285.03333333333336 kroner


In [28]:
import numpy as np

def get_adjective(adj_list):
    i = np.random.randint(len(adj_list))
    return adj_list[i]

get_adjective(['dyr', 'billig', 'pareto optimal', 'høy', 'lav', 'ineffektiv'])

'dyr'

In [29]:
### Oppgave 4a ###
import numpy as np

# Lager en array av tall
x = np.array([1, 2, 3, 4, 5])

# Bruker exponential function (exp) på array'en kalt 'x'
exp_values = np.exp(x)

# Bruker logarithmic function (log) på variabelen 'exp_values'
log_values = np.log(exp_values)

# Sjekker om log_values er det samme som de orginale 'x' verdiene
print(np.allclose(log_values, x))

# Kan også sjekkes ved å printe hver array
print(x)
print(log_values)

True
[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [30]:
### Oppgave 4b ###

# Lager en funksjon som skal ta inn en liste av formen "[x, y, z, ...]"
def percentage_of_two_hundred(x):
    
    # Oppretter en tom liste, som vi skal legge til prosentverdiene til etterpå.
    liste = []
    
    # Vi skal iterere gjennom lista med innput 'x', fra 0'te element til i'te element.
    for i in range(0, len(x)):
        decimal_perc = (x[i]/200)
        perc = round(decimal_perc*100, 2)
        liste.append(perc)
        
    log_liste = np.log(liste)
    return(liste, log_liste)

percentage_of_two_hundred([205, 210, 220, 230, 240])

### Alernativ løsning ###
for i in [205,210,220,230, 240]:
    print(f"i %: {100*(i/200-1)}, i log: {100*np.log(i/200)}")

i %: 2.499999999999991, i log: 2.4692612590371414
i %: 5.000000000000004, i log: 4.879016416943204
i %: 10.000000000000009, i log: 9.531017980432493
i %: 14.999999999999991, i log: 13.976194237515863
i %: 19.999999999999996, i log: 18.232155679395458


In [31]:
def higest_account_balance(x,r,T,n):
    return max((
        account_balance_n(x,r,T,n),
        account_balance_exponential(x,r,T)
    ))
    
print(higest_account_balance(100, 0.2, 4, 1))
account_balance_exponential(100, 0.2, 4)

222.55409284924679


222.55409284924679

In [32]:
values = eval("1, -5, 10")
print(max(values))
print(max(values))
print(np.abs(values))
print(len(values))
print(len("1, -5, 10"))

10
10
[ 1  5 10]
3
9


In [33]:
def present_value(x,r,T,n):
    return x*(1+r/n)**(-T*n)

def present_value_exponential(x,r,T):
    return x*np.exp(-r*T)

In [34]:
def pv_or_balance(x,r,T, return_pv ,n=None):
    if n is None:
        if return_pv:
            return present_value_exponential(x,r,T)
        else:
            return account_balance_exponential(x,r,T)
    else:
        if return_pv:
            return present_value(x,r,T, n)
        else:
            return account_balance_n(x,r,T,n)

        
print( pv_or_balance(100, 0.2, 4, True) )
print( pv_or_balance(100, 0.2, 4, False) )
print( pv_or_balance(100, 0.2, 4, True, 1) )
print( pv_or_balance(100, 0.2, 4, False, 1) )

44.932896411722155
222.55409284924679
48.22530864197532
207.35999999999999


In [35]:
def pv_or_balance(x,r,T ,n=None):
    if n is None:
        return account_balance_exponential(x,r,T)
    else:
        return account_balance_n(x,r,T, n)

    
print( pv_or_balance(100, 0.2, -4) )
print( pv_or_balance(100, 0.2,  4) )
print( pv_or_balance(100, 0.2, -4, 1) )
print( pv_or_balance(100, 0.2,  4, 1) )

44.932896411722155
222.55409284924679
48.22530864197532
207.35999999999999
